# Generated by Django 5.1.4 on 2025-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
